# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-16 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='pago',
            field=models.BooleanField(default=True, verbose_name='Pago'),
        ),
    ]
